language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com

otp_release:
        - 17.1
        - 17.0
        - R16B03
        - R15B03

sudo: false

before_script:
        - make extra-deps
        - make mongooseim-start
        - make

script:
        - make test
        - make ct

after_script:
        - make mongooseim-stop
